version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}

  frontend:
    build: ./front
    ports:
      - "80:80"
    environment:
      - VITE_HOST_ADDRESS=backend
      - SERVER_NAME=localhost
