FROM node:18 AS build

WORKDIR /

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_HOST_ADDRESS
ENV VITE_HOST_ADDRESS=${VITE_HOST_ADDRESS}

RUN npm run build

FROM nginx:alpine

COPY --from=build /dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80